# Generated by Django 2.2.17 on 2021-07-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_want'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='want',
            unique_together=set(),
        ),
    ]
