# Generated by Django 2.2.17 on 2021-08-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0006_notation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='traded',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
