# Generated by Django 2.2.17 on 2021-07-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_github_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='github_url',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='GitHub URL'),
        ),
    ]
