# Generated by Django 2.2.17 on 2021-07-31 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='github_url',
        ),
    ]
