# Generated by Django 2.2.17 on 2021-07-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_github_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='github_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GitHub URL'),
        ),
    ]
